# These variables apply to this entire region. They are automatically pulled in using yamldecode and merged into
# the inputs of the root terragrunt.hcl file.
project_id: "svpc-host"
project_name: "svpc-host"
team: "networking"
ip_cidr_range: 10.0.0.0/8
log_config:
  {
    aggregation_interval: "INTERVAL_1_MIN",
    flow_sampling: 0.5,
    metadata: "INCLUDE_ALL_METADATA",
  }
